"""Fix cloud_pricing unique constraint to include zone

Revision ID: fix_pricing_zone_constraint
Revises: add_spot_price_history
Create Date: 2026-02-04 17:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1x_pr1c1ng_z0ne'  # Shortened to look more like a hash
down_revision = 'add_spot_price_history'
branch_labels = None
depends_on = None


def upgrade():
    """
    Drop old unique constraint and create new one with zone included
    This fixes the issue where spot prices for different zones were treated as duplicates
    
    IMPORTANT: We delete existing spot pricing first to avoid conflicts
    when creating the new constraint
    """
    
    # Use raw SQL to drop and recreate constraint
    # This is more reliable than using Alembic's op functions
    conn = op.get_bind()
    
    # Step 1: Delete existing spot pricing (will be regenerated by scripts)
    # This prevents constraint violations when we add the new constraint
    print("🧹 Clearing existing spot pricing before constraint update...")
    conn.execute(sa.text("""
        DELETE FROM cloud_pricing WHERE pricing_type = 'spot';
    """))
    
    # Step 2: Drop the old constraint if it exists
    print("🔧 Dropping old unique constraint...")
    conn.execute(sa.text("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'uq_cloud_pricing'
            ) THEN
                ALTER TABLE cloud_pricing DROP CONSTRAINT uq_cloud_pricing;
            END IF;
        END $$;
    """))
    
    # Step 3: Create new constraint that includes zone
    print("✅ Creating new unique constraint with zone...")
    conn.execute(sa.text("""
        ALTER TABLE cloud_pricing 
        ADD CONSTRAINT uq_cloud_pricing 
        UNIQUE (provider, instance_type, region, zone, pricing_type, os_type);
    """))
    
    print("🎉 Constraint updated! Spot pricing will be regenerated by data scripts.")


def downgrade():
    """
    Revert to old constraint (without zone)
    """
    
    # Drop the new constraint
    op.drop_constraint('uq_cloud_pricing', 'cloud_pricing', type_='unique')
    
    # Restore old constraint
    op.create_unique_constraint(
        'uq_cloud_pricing',
        'cloud_pricing',
        ['provider', 'instance_type', 'region', 'pricing_type', 'os_type']
    )
